### ISSUE TITLE
Real-time collaboration

### ISSUE THREAD

**Issue by brandonchinn178** [calband/calchart-redesign-old#1]
Allow multiple people to collaborate on a show, in a Google Docs-like interface.

- every action (and other special actions, like selecting dots) posts to server
- everyone currently editing show gets updates and applies the action themselves
- only undo/redo own actions
- read-only, lock sheets when editing

I'm thinking use something like socket.io that uses the WebSockets API

**Comment by noahsark769** [comment]
![image](https://cloud.githubusercontent.com/assets/1168853/22409320/f33429a8-e63c-11e6-8f48-4ad551d2f0da.png)
