### ISSUE TITLE
Shows Won't Open on Safari

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#139]
I can login without an issue. Once in, the document list appears as expected, and when I hover my cursor over a show name, it responds and indicates that I'm hovering over something selectable. Unfortunately, clicking the show name does nothing. Page-wide, the only button that seems to work is the homepage link in the upper left corner.

If you can't recreate the issue easily on another Mac, then I'll try to get more info.

**Comment by brandonchinn178** [comment]
Works on my Mac. If you open the console and do `location.href = "/editor/taylor-swift-show"`, does it work?

@kmdurand
