### ISSUE TITLE
Allow User to Enable/Disable Errors

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#141]
If the sheet I'm working on is still WIP, then I expect a lot of the intermediate edits that I do to produce errors. It would be nice to be able to ignore those errors until I've finished the intermediate edits and am debugging the movement itself.

**Comment by brandonchinn178** [comment]
hmm maybe not preferences, since the user would probably toggle this throughout editing a show. Let's add an item to the Edit Continuity toolbar that toggles showing continuity errors
