### ISSUE TITLE
Hotkey for Locking Stretch Box To Grid

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#144]
This could be useful when I know that I want the edges of my stretched formation to line up with the grid. Even though I could usually use the resnap capability after executing the expansion, having a feature like this would give the user a what-you-see-is-what-you-get experience when using the tool.

**Comment by brandonchinn178** [comment]
Is this just snapping the border of the box? I realized that I couldn't snap all of the dots, since snapping the border of the box will take inner dots off the grid.

@kmdurand
