### ISSUE TITLE
Selecting the 'All' Continuity Should Select All of My Dots

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#145]
When I select the 'Plain' dot type tab in the 'Edit Continuity' mode, all of my Plain dots are selected and highlighted. This doesn't happen for the special case of selecting the 'All' tab.

**Comment by brandonchinn178** [comment]
Would that be helpful? I thought it would be nice to have a tab where none of the dots are highlighted.

@kmdurand
