### ISSUE TITLE
Add minimap navigation

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#146]
Depending on my zoom settings, it is pretty easy to lose yourself outside of the field bounds. It would be nice to have a 'Home' button to bring me back, or just some mechanism to keep me from wandering in the hills if I haven't put anything there.

**Comment by kmdurand** [comment]
On this note, it may be nice to have a 'minimap' of the field that shows where you are currently looking. The map itself could look just like one of the stuntsheet summaries, but could draw a box around the part of the field that can currently be seen given the active zoom setting and location of the user's 'camera'. This minimap could also be used for quick navigation; the user could easily locate parts of the field that are of interest to them, and then perhaps just click on those regions in the minimap to jump there.

**Comment by brandonchinn178** [comment]
:+1:

Maybe add a floating icon to the top-right corner of the editor that, when hovered over, opens a mini-map?
