### ISSUE TITLE
Dot Labels Should Stand Out More

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#148]
I like that you're trying to make them non-obtrusive, because often that's what a charter wants. Nevertheless, there are many times that you need to know who's who, and right now, the dot labels are very tough to read without zooming in and focusing. The color makes it the most difficult to read.

**Comment by brandonchinn178** [comment]
I had this problem too. Let's make the dot labels `$light-gray` and then add a menu item under View labelled "Toggle dot labels". Also under the right click menu
