### ISSUE TITLE
Need a Way to Set Dot Types

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#149]
I'm sure this is on your mind already. I can select dots by dot type, but can't find a way to set the dot types.

**Comment by brandonchinn178** [comment]
Right click -> change dot type. Keyboard shortcuts also available. This is all explained in the [help pages](https://calchart-prod.herokuapp.com/help/editing-dots/change-dot-types/)

![screen shot 2017-05-21 at 4 55 09 pm 2](https://cloud.githubusercontent.com/assets/6827922/26288389/46c0f478-3e46-11e7-9c27-68c8eaf1b1de.png)
