### ISSUE TITLE
Editor Window Real Estate

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#150]
There's a decent amount of open space at the top of the screen, and also to the left, where a summary of stuntsheets is (very beautifully) laid out for the user. The editing space seems small, especially when considering the amount of screen space that a browser already steals from the application in order to display tabs and a URL bar. It would be great to find a way to make the editor window feel bigger, since that is where my focus is when I'm charting. Providing a way to show/hide the stunsheet summary would be a good start.

**Comment by brandonchinn178** [comment]
Yeah! We can do what Google Docs does and provide a toolbar item that hides the top section. And definitely add a toggle sidebar menu item under View
