### ISSUE TITLE
Hotkey for 'Add to Selection'

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#152]
Right now, if I want to select dots A, B, and C, I can select A and B first with the box selection tool, and then hold down a hotkey and box-select dot C to add it to the selection. However, if I first select A and B, and then box-select B and C with the hotkey, the latter operation will deselect dot B and select dot C. It would be nice if there were perhaps another hotkey that let me add all dots within a box selection, instead of toggling whether or not they are selected. It would be nice to have a similar way to deselect dots.

**Comment by brandonchinn178** [comment]
Maybe shift+select adds to selection, ctrl/cmd+shift+select removes from selection, and ctrl/cmd+alt+shift+select toggles selection? Is toggling helpful, or just add/remove from selection?

@kmdurand
