### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#155]
Nice work, Brandon and Team!

This is a beautiful product that you're putting together -- and it's coming together fast! Much of the crucial functionality of old CalChart is already here, and a number of those features have even been improved. The stunsheet browser is beautiful, not to mention helpful (it's much easier to find your stunsheet by-image instead of by-number), and the continuity editor interface is much more human-readable and intuitive. The ability to set default MT orientations and Step Types per-page corresponds very closely with the way we naturally think of stunsheets, and the design decision to keep the editor modal (such that the user must choose between 'Edit Dots' and 'Edit Continuities' at any given time) is easy-to-use and easy-to-understand. 

There's still plenty of work to do (I left you just a few issues ;) ), but I'm looking forward to seeing the quick progress that this continues to make. In particular, I'm excited to watch the collaboration features roll-in, and to see this get integrated with Members Only and the CalChart Online Viewer. Keep up the good work!

Go Bears.
Beat the nostalgia.

- KD

**Comment by brandonchinn178** [comment]
<3 Thanks Kevin!
