### ISSUE TITLE
Creating dot groups

### ISSUE THREAD

**Issue by dpgrubb13** [calband/calchart-redesign-old#193]
Creating dot groups with visible indicators for each group would allow for encoding more information about each dot beyond simply it's dot type.  This would allow for the tracking of basses and perc throughout the show without the use of reference sheets.

**Comment by brandonchinn178** [comment]
Are you thinking like a menu to switch between viewing dot types, instruments, etc?

**Comment by dpgrubb13** [comment]
That might work, but I was thinking more along the lines of having a toggle for maybe a faint halo or some other indicator around each dot group that you've assigned.  The only concern I have about that is that it might make it too cluttered.
