### ISSUE TITLE
CalChart Meeting Jan 21 2018: Can't read dot numbers

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart-redesign-old#214]
This issue is being filed against the NON-REFACTORED staging version of `calchart-redesign`. As the refactored version comes back up-to-speed with the staging version, please note this issue and make sure that it is addressed in the refactored version. This issue may be a duplicate of an already-existing issue, so if that is the case, please acknowledge the original issue number in the comments, and then close this one.

Issue description below:

Dot labels are hard to read. Maybe it's just a coloring issue; or maybe there's something else we can do.

**Comment by brandonchinn178** [comment]
#148
