### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by MichaelTamaki** [calband/calchart-redesign-old#276]
- Download HTML/JS/CSS files and open in file system
    - Export shows/Import shows
    - May be useful for diffing: https://www.npmjs.com/package/jsondiffpatch

**Comment by brandonchinn178** [comment]
Why was this closed?

**Comment by niketkul** [comment]
@brandonchinn178 because we divided it into three individual issues

**Comment by niketkul** [comment]
See #280 #281 #282
